{
  "type": "record",
  "name": "AccountDomainEvent",
  "namespace": "pe.com.scotiabank.tapp.cdc.account",
  "doc": "Carga inicial o cambio incremental de una cuenta.",
  "fields": [
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "AccountChange",
        "fields": [
          {
            "name": "operation",
            "type": {
              "type": "enum",
              "name": "ChangeOperation",
              "symbols": ["SNAPSHOT", "CREATE", "UPDATE", "DELETE"]
            }
          },
          { "name": "entity_id", "type": "string" },
          { "name": "source_version", "type": "long" },
          { "name": "occurred_at", "type": "string" },
          {
            "name": "before",
            "type": [
              "null",
              {
                "type": "record",
                "name": "AccountRecord",
                "fields": [
                  { "name": "account_id", "type": "string" },
                  { "name": "customer_id", "type": "string" },
                  { "name": "masked_number", "type": "string" },
                  {
                    "name": "type",
                    "type": {
                      "type": "enum",
                      "name": "AccountType",
                      "symbols": ["SAVINGS", "CHECKING", "SALARY", "CREDIT", "OTHER"]
                    }
                  },
                  { "name": "currency", "type": "string" },
                  {
                    "name": "status",
                    "type": {
                      "type": "enum",
                      "name": "AccountStatus",
                      "symbols": ["ACTIVE", "DORMANT", "BLOCKED", "CLOSED", "UNKNOWN"]
                    }
                  },
                  { "name": "product_code", "type": "string" },
                  { "name": "branch_code", "type": ["null", "string"], "default": null },
                  { "name": "alias", "type": ["null", "string"], "default": null },
                  { "name": "opened_at", "type": ["null", "string"], "default": null }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "after",
            "type": ["null", "AccountRecord"],
            "default": null,
            "doc": "Es null únicamente para DELETE."
          }
        ]
      }
    },
    {
      "name": "metadata",
      "type": {
        "type": "record",
        "name": "EventMetadata",
        "fields": [
          { "name": "event_id", "type": "string" },
          { "name": "schema_version", "type": "string" },
          { "name": "published_at", "type": "string" },
          { "name": "source_service", "type": "string" },
          { "name": "correlation_id", "type": "string" },
          { "name": "trace_id", "type": ["null", "string"], "default": null },
          { "name": "retry_count", "type": "int", "default": 0 }
        ]
      }
    }
  ]
}
