{
  "type": "record",
  "name": "CustomerDomainEvent",
  "namespace": "pe.com.scotiabank.tapp.cdc.customer",
  "doc": "Carga inicial o cambio incremental de un cliente.",
  "fields": [
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "CustomerChange",
        "fields": [
          {
            "name": "operation",
            "type": {
              "type": "enum",
              "name": "ChangeOperation",
              "symbols": ["SNAPSHOT", "CREATE", "UPDATE", "DELETE"]
            }
          },
          { "name": "entity_id", "type": "string" },
          { "name": "source_version", "type": "long" },
          { "name": "occurred_at", "type": "string" },
          {
            "name": "before",
            "type": [
              "null",
              {
                "type": "record",
                "name": "CustomerRecord",
                "fields": [
                  { "name": "customer_id", "type": "string" },
                  {
                    "name": "document_type",
                    "type": {
                      "type": "enum",
                      "name": "DocumentType",
                      "symbols": ["DNI", "CE", "PASSPORT", "RUC", "OTHER"]
                    }
                  },
                  { "name": "masked_document", "type": "string" },
                  { "name": "given_names", "type": "string" },
                  { "name": "family_names", "type": "string" },
                  {
                    "name": "status",
                    "type": {
                      "type": "enum",
                      "name": "CustomerStatus",
                      "symbols": ["ACTIVE", "INACTIVE", "BLOCKED", "DECEASED", "UNKNOWN"]
                    }
                  },
                  { "name": "segment", "type": ["null", "string"], "default": null },
                  { "name": "masked_email", "type": ["null", "string"], "default": null },
                  { "name": "masked_mobile", "type": ["null", "string"], "default": null }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "after",
            "type": ["null", "CustomerRecord"],
            "default": null,
            "doc": "Es null únicamente para DELETE."
          }
        ]
      }
    },
    {
      "name": "metadata",
      "type": {
        "type": "record",
        "name": "EventMetadata",
        "fields": [
          { "name": "event_id", "type": "string" },
          { "name": "schema_version", "type": "string" },
          { "name": "published_at", "type": "string" },
          { "name": "source_service", "type": "string" },
          { "name": "correlation_id", "type": "string" },
          { "name": "trace_id", "type": ["null", "string"], "default": null },
          { "name": "retry_count", "type": "int", "default": 0 }
        ]
      }
    }
  ]
}
